name: Run Pytest

on:
  workflow_dispatch:

jobs:
  test:
    container:
      image: mambaorg/micromamba:latest

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python environment
      run: micromamba install xarray geopandas pooch matplotlib tqdm pytest ffmpeg netcdf4 pip
      

    - name: Install package in development mode
      run: pip install -e .

    - name: Run pytest
      run: pytest tests/ -v -s
