name: Run pytest

on:
  workflow_dispatch:  # Permet de lancer l'action manuellement

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Micromamba
      uses: mamba-org/provision-with-micromamba@v16
      with:
        environment-file: false  # On crée l'environnement manuellement
        channels: conda-forge
    
    - name: Create environment and install dependencies
      shell: bash -l {0}
      run: |
        micromamba create -n test-env -y python=3.12
        micromamba activate test-env
        micromamba install -y -n test-env pytest xarray ffmpeg geopandas tqdm matplotlib pooch
        pip install -e .
    
    - name: Run pytest
      shell: bash -l {0}
      run: |
        micromamba activate test-env
        pytest -vv -s tests/