name: Python Tests

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Conda environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: "3.12" # Vous pouvez changer cette version de Python si besoin
          channels: conda-forge,defaults
          channel-priority: strict

      - name: Install dependencies
        shell: bash -l {0} # Nécessaire pour que l'environnement conda soit correctement activé
        run: |
          conda install --yes pytest xarray matplotlib geopandas tqdm ffmpeg pooch

      - name: Install package
        shell: bash -l {0} # Assure que l'environnement conda est actif
        run: |
          pip install -e .  # Installe le package dans le répertoire courant en mode editable

      - name: Run pytest
        shell: bash -l {0} # Assure que l'environnement conda est actif
        run: |
          pytest -vv -s
